package com.zdravnica.uikit

const val COUNT_ONE = 1
const val COUNT_TWO = 2
const val COUNT_THREE = 3
const val COUNT_FOUR = 4
const val COUNT_FIVE = 5
const val COUNT_SIX = 6
const val COUNT_TO_100 = 100
const val ANIMATION_DURATION_700 = 700
const val SLIDE_ANIMATION_DURATION_300 = 300
const val ONE_MINUTE_IN_SEC = 60
const val ANIMATION_DURATION_3000 = 3000
const val DELAY_1000_ML = 1000L
const val WHITE_BACK_PROGRESS = 60
const val PINK_BACK_PROGRESS_FROM = 61
const val PINK_BACK_PROGRESS_UNTIL = 88
const val RED_BACK_PROGRESS_FROM = 89
const val RED_BACK_PROGRESS_UNTIL = 99
const val FLOAT_1 = 1f
const val FLOAT_1_6 = 1.6f
const val FLOAT_0_3 = 0.3f
const val FLOAT_140 = 140f
const val FLOAT_160 = 160f
const val MAX_MINUTES = 1800
const val MIN_MINUTES = 600
const val MAX_TEMPERATURE = 80
const val MIN_TEMPERATURE = 40
const val DELAY_DURATION_1500 = 1500L
const val DELAY_DURATION_120000 = 120000L

const val BIG_CHIPS_ICON_DESCRIPTION = "Big chips icon"
const val INDICATOR_ICON_DESCRIPTION = "Indicator Icon"
const val ERROR_ICON_DESCRIPTION = "Error Icon"
const val TEMPERATURE_ICON_DESCRIPTION = "Temperature Icon"
const val CLOSE_ICON_DESCRIPTION = "Close Icon"
const val TOP_APP_BAR_TEMPERATURE_DESCRIPTION = "Top App Bar Temperature Icon"
const val TOP_APP_BAR_MENU_ICON_DESCRIPTION = "Top App Bar Menu Icon"
const val GRADIENT_ICON_BUTTON_DECREASE_DESCRIPTION = "Gradient Icon Button Decrease"
const val GRADIENT_ICON_BUTTON_INCREASE_DESCRIPTION = "Gradient Icon Button Increase"
const val BLUETOOTH_ICON_DESCRIPTION = "Icon bluetooth"
const val APP_LOGO_DESCRIPTION = "App logo"
const val ORDER_DESCRIPTION = "Order button"
const val CHOOSE_EMAIL_APP = "Choose Email App"
const val NO_EMAIL_APP = "No email app found"
const val EMAIL_DATA = "message/rfc822"
const val PHONE_CALL_DATA = "tel:"